version: '3'

services:
    app:
        image: node:7.10
        volumes:
            - ./:/app
            - node_modules:/app/node_modules
        networks:
            - app
        ports:
            - "127.0.0.1:5678:5678"
        command: bash -c "cd /app && yarn && yarn start"
    mariadb:
        image: mariadb:10.1
        environment:
            - MYSQL_ROOT_PASSWORD=puuppa
            - MYSQL_DATABASE=teamdaily
            - MYSQL_USER=teamdaily
            - MYSQL_PASSWORD=passu!1
        volumes:
            - ./database_dump:/docker-entrypoint-initdb.d
            - mariadb:/var/lib/mysql
        networks:
            - app
        command: --silent-startup
        ports:
            - "127.0.0.1:6789:3306"

volumes:
    node_modules:
    mariadb:
    
networks:
    app:
